#!/usr/bin/env php
<?php

define('HANDLE_BASE_PATH', dirname(__FILE__));

require __DIR__ . '/vendor/autoload.php';

$app = new \Symfony\Component\Console\Application();
foreach (glob(HANDLE_BASE_PATH . '/src/Commands/*.php') as $file) {
    $className = '\\Handle\\Commands\\' . basename($file, '.php');
    $app->add(new $className);
}
$app->run();